#!/usr/bin/env bash
set -euo pipefail

# Render nginx config for single-domain deployment:
# - static frontend via nginx root
# - backend/socket proxied to localhost:<backend-port>

DOMAIN="poker.bodhix.io"
BACKEND_PORT="3101"
WEB_ROOT="/var/www/poker/web/dist"
SSL_ENABLED="true"

is_uint() {
  [[ "$1" =~ ^[0-9]+$ ]]
}

usage() {
  cat <<'EOF'
Usage:
  ./scripts/vps/render-nginx-config.sh [options]

Options:
  --domain <domain>          Domain name (default: poker.bodhix.io)
  --backend-port <port>      Backend localhost port (default: 3101)
  --web-root <path>          Static frontend root (default: /var/www/poker/web/dist)
  --ssl-enabled <true|false> Generate HTTPS server block (default: true)
  -h, --help                 Show this help

Example:
  ./scripts/vps/render-nginx-config.sh --domain poker.bodhix.io --backend-port 3275 --ssl-enabled false > /tmp/poker.conf
EOF
}

require_option_value() {
  local flag="$1"
  local value="${2-}"
  if [[ -z "$value" || "$value" == --* ]]; then
    echo "Missing value for $flag" >&2
    usage
    exit 2
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain)
      require_option_value "$1" "${2-}"
      DOMAIN="$2"
      shift 2
      ;;
    --backend-port)
      require_option_value "$1" "${2-}"
      BACKEND_PORT="$2"
      shift 2
      ;;
    --web-root)
      require_option_value "$1" "${2-}"
      WEB_ROOT="$2"
      shift 2
      ;;
    --ssl-enabled)
      require_option_value "$1" "${2-}"
      SSL_ENABLED="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 2
      ;;
  esac
done

if ! is_uint "$BACKEND_PORT"; then
  echo "Backend port must be numeric: $BACKEND_PORT" >&2
  exit 2
fi

if [[ "$SSL_ENABLED" != "true" && "$SSL_ENABLED" != "false" ]]; then
  echo "--ssl-enabled must be true or false" >&2
  exit 2
fi

if [[ "$SSL_ENABLED" == "true" ]]; then
cat <<EOF
# Generated by scripts/vps/render-nginx-config.sh
# Domain: $DOMAIN
# Backend: 127.0.0.1:$BACKEND_PORT
# Frontend root: $WEB_ROOT
# SSL: enabled

server {
  listen 80;
  listen [::]:80;
  server_name $DOMAIN;

  # Certbot challenge path
  location /.well-known/acme-challenge/ {
    root /var/www/html;
  }

  location / {
    return 301 https://\$host\$request_uri;
  }
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name $DOMAIN;

  # Replace with your certificate paths (or use certbot --nginx)
  ssl_certificate     /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;

  # Frontend static app
  root $WEB_ROOT;
  index index.html;

  # Health endpoint from backend
  location = /health {
    proxy_pass http://127.0.0.1:$BACKEND_PORT/health;
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
  }

  # Optional API prefix passthrough
  location /api/ {
    proxy_pass http://127.0.0.1:$BACKEND_PORT/api/;
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
  }

  # Socket.IO websocket + polling
  location /socket.io/ {
    proxy_pass http://127.0.0.1:$BACKEND_PORT/socket.io/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_read_timeout 86400;
  }

  # SPA fallback
  location / {
    try_files \$uri \$uri/ /index.html;
  }
}
EOF
else
cat <<EOF
# Generated by scripts/vps/render-nginx-config.sh
# Domain: $DOMAIN
# Backend: 127.0.0.1:$BACKEND_PORT
# Frontend root: $WEB_ROOT
# SSL: disabled (bootstrap mode)

server {
  listen 80;
  listen [::]:80;
  server_name $DOMAIN;

  # Certbot challenge path
  location /.well-known/acme-challenge/ {
    root /var/www/html;
  }

  # Frontend static app
  root $WEB_ROOT;
  index index.html;

  # Health endpoint from backend
  location = /health {
    proxy_pass http://127.0.0.1:$BACKEND_PORT/health;
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
  }

  # Optional API prefix passthrough
  location /api/ {
    proxy_pass http://127.0.0.1:$BACKEND_PORT/api/;
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
  }

  # Socket.IO websocket + polling
  location /socket.io/ {
    proxy_pass http://127.0.0.1:$BACKEND_PORT/socket.io/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_read_timeout 86400;
  }

  # SPA fallback
  location / {
    try_files \$uri \$uri/ /index.html;
  }
}
EOF
fi
